import { makeStyles } from '@mui/styles';
import { NAVBAR } from '../../config';

const useStyles = makeStyles((theme) => ({
  ctnRoot: {
    position: 'relative',
    background: '#fff',
    paddingBottom: 60,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    [theme.breakpoints.up('xl')]: {
      paddingRight: NAVBAR.DASHBOARD_COLLAPSE_WIDTH,
    },
    [theme.breakpoints.down('xl')]: {
      paddingRight: 20,
    },
  },
  ctnWrapper: {
    maxWidth: '1366px',
    margin: 'auto',
    backgroundColor: '#E4E6FA',
    padding: 20,
    marginTop: 20,
    marginBottom: 20,
    borderRadius: 20,
    marginLeft: 20,
    marginRight: 20,
    width: '100%',
    boxShadow: '0px 10px 20px rgba(114, 125, 196, 0.5)',
  },
  ctnSection: {
    display: 'flex',
    backgroundColor: '#fff',
    boxShadow: '0px 10px 20px rgba(114, 125, 196, 0.5)',
    marginLeft: 20,
    marginRight: 20,
    marginBottom: 20,
    padding: 20,
    borderRadius: 20,
  },
  ctnIcon: {
    marginRight: 40,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    '& > img': {
      width: 70,
      height: 60,
      objectFit: 'contain',
      margin: 'auto',
    },
  },
  ctnMidInput: {
    flexGrow: 1,
    paddingRight: 20,
  },
  ctnRightInput: {
    minWidth: '20%',
  },
  ctnGray: {
    maxWidth: '100%',
    '& > input': {
      fontFamily: 'Public Sans,sans-serif',
      border: 0,
      height: 44,
      width: '100%',
      background: '#F1F1F1',
      borderRadius: 8,
      paddingLeft: 12,
      paddingRight: 12,
      fontSize: 15,
    },
  },
  ctnDate: {
    background: '#F1F1F1',
    height: 44,
    borderRadius: 8,
    paddingLeft: 12,
    paddingRight: 12,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    '& > img': {
      width: 18,
      height: 18,
      objectFit: 'contain',
    },
  },
  containerDate: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    '& > .react-datepicker-wrapper > .react-datepicker__input-container > input': {
      width: '120px',
      height: 44,
      background: 'transparent',
      border: 0,
      fontFamily: 'Public Sans,sans-serif',
      fontSize: 14,
      outline: 'none',
    },
  },
  availWrapper: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  inputGray: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    display: 'flex',
    background: '#F1F1F1',
    height: 44,
    // paddingLeft: 12,
    paddingRight: 12,
    borderRadius: 8,
    marginRight: 40,
    width: '100%',
    [theme.breakpoints.down('md')]: {
      maxWidth: '240px',
    },
  },
  leftWrapper: {
    display: 'flex',
    paddingLeft: 12,
    '& > img': {
      width: 22,
      height: 22,
      objectFit: 'contain',
      marginRight: 12,
    },
  },
  midWrapper: {
    paddingLeft: 12,
    marginRight: 12,
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    // background: 'yellow',
    '& > input': {
      fontFamily: 'Public Sans,sans-serif',
      border: 0,
      height: 30,
      width: 44,
      background: '#fff',
      borderRadius: 8,
      marginLeft: 12,
      marginRight: 12,
      fontSize: 15,
      outline: 'none',
      textAlign: 'center',
    },
    '& > span': {
      '& > b': {
        marginLeft: 12,
        marginRight: 12,
      },
    },
  },
  unactiveInput: {
    '& > input': {
      color: '#808080',
      background: '#F1F1F1 !important',
    },
  },
  altDateWrapper: {
    display: 'flex',
    alignItems: 'center',
    marginLeft: 30,
    '& > img': {
      width: 20,
      height: 20,
      objectFit: 'contain',
      marginLeft: 14,
    },
  },
  ctnDefineAudience: {
    background: 'rgb(45, 49, 151, 0.1)',
    marginLeft: 0,
    marginRight: 0,
    paddingTop: 20,
    paddingBottom: 20,
    borderRadius: 20,
    marginBottom: 20,
  },

  ctnSectionTarget: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    boxShadow: '0px 10px 20px rgba(114, 125, 196, 0.5)',
    marginLeft: 20,
    marginRight: 20,
    marginBottom: 20,
    // padding: '12px 20px 16px 20px',
    padding: 20,
    borderRadius: 20,
  },
  ctnIconTarget: {
    marginRight: 40,
    '& > img': {
      width: 100,
      height: 100,
      objectFit: 'contain',
    },
  },

  ctnIconTargetAlt: {
    marginRight: 40,
    '& > img': {
      width: 190,
      height: 80,
      objectFit: 'contain',
    },
  },
  ctnIconInformation: {
    '& > img': {
      width: 190,
      height: 80,
      objectFit: 'contain',
    },
  },
  ctnInputBudget: {
    display: 'flex',
    alignItems: 'center',
    height: '100%',
  },
  ctnTotal: {
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    borderRight: '1px solid #667C8B',
    paddingRight: 120,
    marginRight: 120,
  },
  ctnHorizontalRow: {
    marginLeft: 120,
    marginRight: 120,
    backgroundColor: '#000',
    width: 1,
    height: '100%',
  },
  ctnDesc: {
    display: 'flex',
    flexDirection: 'column',
  },
  inputCollectionCard: {
    display: 'flex',
    backgroundColor: '#fff',
    boxShadow: '0px 10px 20px rgba(114, 125, 196, 0.5)',
    marginLeft: 20,
    marginRight: 20,
    marginBottom: 20,
    padding: 20,
    borderRadius: 20,
    flexDirection: 'column',
    position: 'relative',
  },
  ctnInputCollectionPageWrapper: {
    width: '100%',
    display: 'flex',
    [theme.breakpoints.down('md')]: {
      flexDirection: 'column',
    },
  },
  ctnInputCollection: {
    marginBottom: 24,
  },
  ctnLeftCollection: {
    width: '50%',
    paddingRight: 40,
    display: 'flex',
    flexDirection: 'column',
    [theme.breakpoints.down('md')]: {
      width: '100%',
      paddingRight: 0,
    },
  },
  rowTitleWrapper: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    position: 'relative',
  },
  leftTitle: {
    display: 'flex',
    alignItems: 'center',
    position: 'relative',
    '& > img': {
      width: 16,
      height: 16,
      objectFit: 'contain',
      marginLeft: 8,
      cursor: 'pointer',
    },
    '& > div': {
      position: 'relative',
    },
  },
  leftTitleBetween: {
    display: 'flex',
    alignItems: 'center',
    width: '100%',
    fontFamily: 'Public Sans,sans-serif',
    justifyContent: 'space-between',
    '& > img': {
      width: 16,
      height: 16,
      objectFit: 'contain',
      marginLeft: 8,
      cursor: 'pointer',
    },
    '& > div': {
      position: 'relative',
    },
  },
  leftTitleAdText: {
    display: 'flex',
    alignItems: 'center',
    position: 'absolute',
    top: -5,
    marginTop: 10,
    '& > img': {
      width: 16,
      height: 16,
      objectFit: 'contain',
      marginLeft: 8,
      cursor: 'pointer',
    },
    '& > div': {
      position: 'relative',
    },
  },
  inputCollectionWrapper: {
    '& > input': {
      fontFamily: 'Public Sans,sans-serif',
      border: 0,
      height: 44,
      width: '100%',
      background: '#F1F1F1',
      borderRadius: 8,
      paddingLeft: 12,
      paddingRight: 12,
    },
  },
  inputCollectionIcon: {
    display: 'flex',
    alignItems: 'center',
    background: '#F1F1F1',
    height: 44,
    borderRadius: 8,
    paddingLeft: 12,
    marginBottom: 8,
    '& > img': {
      width: 25,
      height: 25,
      objectFit: 'contain',
    },
    '& > input': {
      fontFamily: 'Public Sans,sans-serif',
      border: 0,
      width: '100%',
      height: 44,
      background: '#F1F1F1',
      paddingLeft: 12,
      paddingRight: 12,
      outline: 'none',
    },
  },
  textAreaCollection: {
    '& > textarea': {
      border: 0,
      height: 120,
      width: '100%',
      background: '#F1F1F1',
      borderRadius: 8,
      paddingLeft: 12,
      paddingRight: 12,
      fontFamily: 'Public Sans,sans-serif',
      paddingTop: 20,
      paddingBottom: 20,
    },
  },
  ctnRightCollection: {
    width: '50%',
    [theme.breakpoints.down('md')]: {
      width: '100%',
      paddingRight: 0,
    },
  },
  ctnSelectAudience: {
    borderTop: '1px solid #C9D3D8',
    paddingTop: 20,
    marginTop: 4,
  },
  ctnAudienceItem: {
    height: 44,
    background: '#F1F1F1',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    cursor: 'pointer',
  },
  btnCreateAd: {
    display: 'flex',
    backgroundColor: '#fff',
    boxShadow: '0px 10px 20px rgba(114, 125, 196, 0.5)',
    marginLeft: 20,
    marginRight: 20,
    marginBottom: 20,
    padding: 20,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    cursor: 'pointer',
    '& > img': {
      width: 44,
      height: 44,
      objectFit: 'contain',
      marginRight: 12,
    },
  },
  setupAirdropWrapper: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    paddingBottom: 40,
    '& > div': {
      width: 'auto',
      paddingLeft: 100,
      paddingRight: 100,
      borderRadius: 12,
    },
  },
  btnSetupAirdrop: {
    height: 44,
    width: 'auto !important',
    borderRadius: 12,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    paddingLeft: 100,
    paddingRight: 100,
    cursor: 'pointer',
  },
  datepickerStyle: {
    overflow: 'hidden',
    width: 0,
    height: 0,
    position: 'absolute',
  },
  ctnRowAudience: {
    display: 'flex',
    alignItems: 'stretch',
    marginBottom: 30,
    flexWrap: 'wrap',
    paddingRight: 20,
  },
  ctnTitle: {
    display: 'flex',
    alignItems: 'center',
    paddingLeft: 20,
    paddingRight: 20,
  },
  rowTitle: {
    height: '2px',
    background: '#fff',
    flexGrow: 1,
  },
  ctnAudienceStyle: {
    paddingTop: 20,
  },
  ctnDisable: {
    background: '#C8C8C8',
  },
  unactiveChecbox: {
    '& > div > span': {
      color: '#808080',
    },
    '& > div > div > .react-datepicker-wrapper > .react-datepicker__input-container > input': {
      color: '#808080',
    },
  },
  fixedWidth: {
    width: '100%',
  },
  gridAvailability: {
    [theme.breakpoints.down('md')]: {
      '& .MuiGrid-item:not(:first-child)': {
        paddingTop: 12,
      },
    },
  },
  ctnSectionAd: {
    paddingRight: 20,
  },
  txtAudienceOptimized: {
    '& > span': {
      color: '#90B272',
      marginRight: 4,
      fontWeight: 'bold',
      fontSize: 15,
    },
  },
  ctnAdAudience: {
    position: 'relative',
  },
  txtAudienceTargeting: {
    '& > span': {
      color: '#8C65CC',
      marginRight: 4,
      fontWeight: 'bold',
      fontSize: 15,
    },
    textOverflow: 'ellipsis',
    display: '-webkit-box',
    WebkitBoxOrient: 'vertical',
    WebkitLineClamp: 2,
    textAlign: 'center',
    overflow: 'hidden',
  },
  txtUserAirdrop: {
    '& > span': {
      fontWeight: '800',
    },
  },
  ctnRedBorder: {
    border: '2px solid red',
  },
  ctnPopover: {
    '& > .MuiPaper-root': {
      background: 'rgba(0, 0, 0,0.9)',
      boxShadow: ' rgba(0, 0, 0, 0.1) 0px 10px 15px -10px, rgba(0, 0, 0, 0.05) 0px 4px 6px -2px',
    },
  },
  ctnPopoverError: {
    '& > .MuiPaper-root': {
      background: '#FFD8DF',
      boxShadow: ' rgba(0, 0, 0, 0.1) 0px 10px 15px -10px, rgba(0, 0, 0, 0.05) 0px 4px 6px -2px',
    },
  },
  ctnInputColumn: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    '& > #red-alert': {
      color: '#E83155',
      fontSize: 14,
      marginTop: 6,
    },
  },
  ctnRedBorderInput: {
    border: '1px solid #E83155',
  },
  ctnError: {
    marginTop: 4,
    '& > span': {
      color: '#E83155',
      fontSize: 14,
    },
  },
  ctnDeleteADs: {
    position: 'absolute',
    top: 10,
    right: 20,
  },
  ctnIconDeletAds: {
    width: 30,
    height: 30,
    background: '#000',
    borderRadius: 30 / 2,
    padding: 6,
    cursor: 'pointer',
  },
  ctnCounter: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 10,
  },
  ctnCollectionBottomHeaderContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    '& > div': {
      display: 'flex',
      width: '100%',
      marginTop: 10,
    },
  },
  leftTitleBottom: {
    display: 'flex',
    alignItems: 'center',
    position: 'relative',
    marginBottom: 5,
    '& > img': {
      width: 12,
      height: 12,
      objectFit: 'contain',
      marginLeft: 4,
      cursor: 'pointer',
      marginBottom: 3,
    },
    '& > div': {
      position: 'relative',
    },
  },
  ctnAdCollection: {
    width: '100%',
    paddingRight: 40,
    display: 'flex',
    flexDirection: 'row',
    [theme.breakpoints.down('md')]: {
      width: '100%',
      paddingRight: 0,
    },
  },
  adtextTitleContainer: {
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'center',
    height: 20,
    marginTop: 15,
    '& > img': {
      cursor: 'pointer',
      marginLeft: 10,
    },
  },
  adTextTitle: {
    fontFamily: 'Public Sans, sans-serif',
    color: '#808080',
    marginBottom: 20,
  },
  addAdButton: {
    border: 0,
    height: 120,
    width: '100%',
    background: '#F1F1F1',
    borderRadius: 8,
    paddingLeft: 12,
    paddingRight: 12,
    fontFamily: 'Public Sans,sans-serif',
    paddingTop: 20,
    paddingBottom: 20,
    cursor: 'pointer',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    '& > img': {
      width: 25,
      marginRight: 10,
    },
  },
}));

export default useStyles;
