export const routes = {
  login: '/login',
  register: '/create-account',
  createCampaign: '/create-campaign',
  invoices: '/invoices',
  settings: '/settings',
  privacy: '/privacy',
  forgotPassword: '/forgot-password',
  changePassword: '/change=passwprd',
  walletads: 'https://walletads.io/',
  walletadsDashboard: 'https://dashboard.walletads.io/',
  walletadsFeature: 'https://www.walletads.io/#features',
  walletadsExplore: 'https://www.walletads.io/#explore',
  walletadsContact: 'https://www.walletads.io/#signup',
  walletadsLogin: 'https://dashboard.walletads.io/',
};
